### ISSUE TITLE
Can't increase timeout

### ISSUE THREAD

**Issue by chriscollinsboxuk** [jonkemp/node-qunit-phantomjs#12]
I don't think it's possible to increase the timeout via a commandline argument.  From reading the source, it looks as though the only arguments that are passed through to the index.js file from the bin/node-qunit-phantomjs file are the name of the file and the verbose argument: The timeout argument is discarded.

If I've misread the code and it is possible to do this, I'd love to know how to do this!

Thanks.

**Comment by bobbyg603** [comment]
+1

**Comment by jonkemp** [comment]
No, but it could be added fairly easily. I'll add it as a feature request. If you could change the wording of the issue, that would help.

**Comment by bobbyg603** [comment]
Awesome! Thank you Jon!
