### ISSUE TITLE
Upgrade PhantomJS

### ISSUE THREAD

**Issue by dethe** [jonkemp/node-qunit-phantomjs#18]
PhantomJS is at 2.0 now, and older versions do not support MutationObserver (and probably other things, but that's what bit me). Test runner is picking up my local PhantomJS and passing, then failing CI tests on Github.

**Comment by dethe** [comment]
Investigating further, it looks like this is blocked by the npm release of PhantomJS: https://github.com/Medium/phantomjs/issues/288.

**Comment by jonkemp** [comment]
Current version of the phantomjs package is at 2.1.3. Can you change the title of this issue to 'Upgrade PhantomJS'?

**Comment by epicmiller** [comment]
Any update in this? Its biting me in the ass too :)

**Comment by jbmurray** [comment]
Me too! An update or ETA would be great! Thanks

**Comment by epicmiller** [comment]
Its already updated in the package.json, we just need a release :)

**Comment by jonkemp** [comment]
Done in v1.3.1. 8286f38

**Comment by dethe** [comment]
Yeah! Thank you. :balloon: :tada: :fireworks:
