### ISSUE TITLE
"env: node\r: No such file or directory"

### ISSUE THREAD

**Issue by jackfranklin** [jonkemp/node-qunit-phantomjs#2]
Hello,

I have installed node-qunit-phantomjs locally and am trying to run it like so:

`./node_modules/.bin/node-qunit-phantomjs mytests.html`

However, everytime I get the error:

```
"env: node\r: No such file or directory"
```

A quick Google suggests this is something to do with line endings: https://github.com/krasimir/absurd/issues/20.

**Comment by mathslimin** [comment]
if you are in mac os x , you can download from http://phantomjs.org/download.html , homebrew install package has this bug
