### ISSUE TITLE
More than one phantomjs options

### ISSUE THREAD

**Issue by migacz1125** [jonkemp/node-qunit-phantomjs#23]
I have problem if i add more than one phantomjs option, example here:

`qunit('./webapp/test/unit/index.qunit.html', { 'verbose': true, 'phantomjs-options': ["--debug=true", "--web-security=false"] });`

**Comment by jonkemp** [comment]
This was done recently in the gulp-quint plugin. We just need to implement this same functionality here.

https://github.com/jonkemp/gulp-qunit/pull/30

**Comment by jonkemp** [comment]
Done in 1.6.0.

https://github.com/jonkemp/node-qunit-phantomjs/releases/tag/v1.6.0
