### ISSUE TITLE
npm script wildcard input?

### ISSUE THREAD

**Issue by XhmikosR** [jonkemp/node-qunit-phantomjs#28]
Hi, @jonkemp.

So, I've been trying to move to npm scripts for bootlint. See this branch https://github.com/twbs/bootlint/tree/npm-scripts

So, in the commandline I tried using

```json
"qunit": "node-qunit-phantomjs \"test/fixtures/**/*.html\" --timeout=10",
```

but that doesn't work. If I specify only one input html file it works.

Is there some way to achieve this without using gulp/grunt and friends?

**Comment by jonkemp** [comment]
It's just passing that path to phantomjs, so it depends on if phantomjs will accept it or not. It looks to me like it won't. I'll look at it more, but I'm not a phantomjs expert.

http://phantomjs.org/api/command-line.html

**Comment by XhmikosR** [comment]
Yeah, I noticed it too and I came up with a simple wrapper script around your package.

https://github.com/twbs/bootlint/pull/405/commits/d6342da9b69168d404033079600a2ed69c820ff2

**Comment by XhmikosR** [comment]
Hmm, shouldn't the callback option be documented?

**Comment by jonkemp** [comment]
Yes, you're right it should be. I've never noticed that before. It only works if you are requiring it as a module though, not via command line.

**Comment by XhmikosR** [comment]
Yeah, as a module that's how I'm using it there too. It's just that I had trouble with async since it took me a while to figure out your module accepts a callback :P
