### ISSUE TITLE
error colorization

### ISSUE THREAD

**Issue by FND** [jonkemp/node-qunit-phantomjs#4]
It'd be nice to *optionally* highlight failures, i.e. lines like

> Failed assertion: expected: 2, but was: 1

or 

> Took 28ms to run 7 tests. 6 passed, 1 failed.

I'm not sure how best to implement that though.

**Comment by jonkemp** [comment]
I just added support for this but as a feature, not as an option. 

@FND @kimagure or anyone else want to test it and let me know what you think before I publish it? You can test it via the latest version of this repo.

**Comment by FND** [comment]
Looks good to me, thanks!

One detail though:

> Took 23 ms to run 2 tests. 2 passed, 0 failed.

Highlighting the zero in red somewhat defeats the purpose; IMO red should only appear if something went wrong.

**Comment by jonkemp** [comment]
@FND but you can also have this output, if tests do fail:

> Took 6 ms to run 10 tests. 9 passed, 1 failed.

What do you think should happen in that case?

**Comment by FND** [comment]
In that case, I would want that number to be red. So basically `color = failed > 0 ? "red" : default`.

In fact, I'd probably colorize that entire summary line depending on the results: green if all tests passed, red otherwise.

**Comment by jonkemp** [comment]
@FND ok, thanks for your feedback!

**Comment by jonkemp** [comment]
Resolved in [v1.2.0](https://github.com/jonkemp/node-qunit-phantomjs/releases/tag/v1.2.0).
